package com.revature.trms.util;

public enum RequestStatus
{
	NEEDS_SUPERVISOR_APPROVAL,
	NEEDS_DEPARTMENT_APPROVAL,
	NEEDS_BENEFITS_COORDINATOR_APPROVAL,
	NEEDS_PROOF_OF_COMPLETION,
	DENIED,
	AWARDED
}
